// btn.addEventListener('click', (eve)=>{
//     let Model = model.value;
//      let Price = Number(price.value);
//      for(let i=0; i < localStorage.length; i++){   
//     carData.filter((data)=>{
//        if(data.Model === Model && data.Price === Price){
//         }
//     })   
// }
//  eve.preventDefault();
// })




// carData = []
// for(let i = 0; i< localStorage.length; i++){
//     let retrieveData = JSON.parse(localStorage.getItem(`data${count}`))
//     carData.push(retrieveData)
//     console.log(carData)
// }
// carData = []
// for(let i = 0; i< localStorage.length; i++){
//     let retrieveData = JSON.parse(localStorage.getItem(`data${count}`))
//     carData.push(retrieveData)
//     console.log(carData)
    
// }


// console.log(carData)

//  modelData = [];
//  let Model = model.value
//  for (let i = 0; i=localStorage.length; i++){
//    modelData.filter((Model)=>{
//      let retrieveData = JSON.parse(localStorage.getItem(`data${count}`))
//      modelData.push(Model)
//      console.log()
//    })
    // modelname.innerHTML = modelData.filter(modelValue);
    
    // function modelValue(value){
    //     return value = Model;
    // }
    
    
    // modelname.innerHTML = modelData.filter(modelValue);
    
    // function modelValue(modeldata){
    //     return modeldata = modelData(model.value);
    // }
// //console.log(retrieveData.Model)
// const result = modelData.filter(model => retrieveData < 2);
// console.log(result)
    // for(let m = 0; m = modelData.length; m++){
    //     console.log('I entered here')
    // let retrieveData = JSON.parse(localStorage.getItem(`data${m}`))
    // console.log(retrieveData)
    //     // modelValue.push(retrieveData.Model)       
    //     // console.log(modelValue)
    // }
    
    // var modelName = modelData.filter(function(model){
    //     return model.Model == "dell";
    // })
    // console.log(modelName)
    // var numbers = [1, 3, 6, 8, 11]
    
    // var greaterThanSeven = numbers.filter(function(number){
    //     return number > 7;
    // });
    // console.log(greaterThanSeven)
    
    // var creatures = [
    //     {name: "shark", habitat: "Ocean"},
    //     {name: "whale", habitat: "Ocean"},
    //     {name: "lion", habitat: "savanna"},
    //     {name: "monkey", habitat: "jungle"}
    // ]
    // var aquaticCreatures = creatures.filter(function(creature){
    //     return creature.habitat == "Ocean";
    // });
    // console.log(aquaticCreatures)
// }
        // modelData.forEach((data) => {
        //     for(let i = 0; i < modelValue.length; i++){
        //         if(data.Model === modelData[i].Model) {
        //             check = true
        //             console.log(check)
        //         }
        //     }
        
        //     if (!check === true){
        //         console.log('I entered here')
        //         console.log(data.Model)
        //         modelValue.push(data.Model);
        //         console.log(modelValue)
        //     }
        //     check = false
        //     } 